apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: jenkinsOSS
          artifact-id: b0ec36cd-0b36-4435-8d51-92b1427bae52
          target-environment: Pre-Prod